<?php

namespace Database\Seeders\AlmacenGeneral;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class table_ProveedoresSeeder extends Seeder
{
    public function run(): void
    {
        $proveedores = [
            'ALL PHARMA S.A. DE C.V.',
            'LABORATORIOS PISA S.A. DE C.V.',
            'BIO STERIL SA DE CV',
            'ADRIANA PEREZ JIMENEZ',
            'AGUSTIN RAFAEL ZURITA OJEDA',
            'ALAMBRADOS MEXICANOS S.A. DE C.V.',
            'ANALISIS DE AGUA, S.A. DE C.V.',
            'ATMOSFERA CORPORATIVA SA DE CV',
            'ARCOTH M2 SAS DE CV',
            'BERKLEY INTERNACIONAL FINANZAS MEXICO SA DE CV',
            'BOLPACK INTERNACIONAL SA DE CV',
            'BUFETE ROBLES LEON SC',
            'CARLOS NAFARRATE SA DE CV',
            'CORPORATIVO DE CALIDAD EN MOBILIARIO SA DE CV',
            'D2 SEGURIDAD PRIVADA SA DE CV',
            'DEWIMED SA',
            'FUMIINOVA SA',
            'GABRIEL DELGADO ALONSO',
            'GRAFICOS E IMAGEN DIGITAL SA DE CV',
            'COMERCIALIZACI?N DE SISTEMAS DE INFORM?TICA, S.A. DE CV',
            'MARIA DE LOURDES NARVAEZ PELAEZ',
            'INOXIDABLE CEAL S. DE R.L. DE C.V.',
            'JORDI FELIPE DE JESUS ASCENCIO ESPINOZA',
            'KARINA YEDITH SANCHEZ QUERO',
            'KC RENTAS, S.A. DE C.V.',
            'ASESOR?A LIMAC, S.A. DE C.V.',
            'LUIS ENRIQUE ALCAZAR PADILLA',
            'MARIO ESCOBAR GARZON',
            'RUVALCABA PRECIADO MARIO',
            'NAVARRO CONTADORES CONSULTORES SC',
            'NORMA CONSUELO FONTES MARTINEZ',
            'RVG SOLUTIONS S.A. DE C.V.',
            'JUAN FRANCISCO RIVAS GUZMAN',
            'ROSELIA SANTANA ABARCA',
            'SANTIAGO GARCIA ACOSTA',
            'SEPIA COMERCIALIZADORA E IMPORTADOR A S.A. DE C.V.',
            'PRODUCTOS JURIDICO CORPORATIVOS, SC',
            'SERGIO OROZCO ORNELAS',
            'SOLUCIONES  INTEGRALES DATA NET, S.A. DE C.V.',
            'SEGUROS  SURA S.A. DE C.V.',
            'TOTAL PLAY TELECOMUNICACIONES S.A. DE C.V.',
            'BEATRIZ HUEY TZITLALIN GAYTAN GUTIERREZ',
            'UNIDAD DE PATOLOGIA  CLINICA  E IMAGENIOLOGIA, S.C.',
            'VALSI AGRICOLA INDUSTRIAL SA DE CV',
            'VANRENTA S.A. DE C.V',
            'VERSA MUEBLES PARA OFINA S.A. DE C.V.',
            'VICTOR HUGO LOPEZ MIRANDA',
            'COMERCIALIZADORA INTERNACIONAL PURI SA',
            'NUEVA WALMART DE MEXICO, S DE RI DE CV',
            'MEDIMARCAS S.A DE C.V.',
            'COSTCO DE MEXICO, S.A DE C.V',
            'TIENDAS CUPRUM SA DE CV',
            'MARMAQ MAYOREO DE REFRIGERACION Y MAQUINAS, S.A. DE C.V.',
            'HOME DEPOT MEXICO S. R.L DE C.V.',
            'LIMPRO COMERCIAL SA DE CV',
            'CHEFS TOYS',
            'PRESTACIONES MEDICAS IQUEST',
            'GOMEZ CORNELIO ALONDRA',
            'EQUIPOS INTERFERENCIALES',
            'INTEGRACION DE TECNOLOGIA MEDICA SA DE CV',
            'GRUPO INDUSTRIAL JOME SA DE CV',
            'SAMUEL HUERTA TREVI?O',
            'COMPUCAD INFRAESTRUCTURA Y SOLUCIONES',
            'ATL JALISCO, SA DE CV',
            'JORDI FELIPE DE JESUS ASCENCIO ESPINO',
            'DORMISTAR',
            'CONSULTORIA BIOMEDICA INTEGRAL SA DE CV',
            'OFFICE MAX',
            'MANUFACTURERA ALEAR SA DE CV',
            'QUALITY MED, SA DE CV',
            'GRUPO HABITAT CONTROL SA DE CV',
            'INOVACION Y DESARROLLO EN SISTEMAS DE VANGUARDIA, S.A DE C.V.',
            'DICOTECH MAYORISTA DE TECNOLOGIA S.A. DE C.V.',
            'WALI (SATTLER TECH CORP)',
            'MA. EVA JANETTE LICEA GAYTAN',
            'KINGSTRONG NOGA? BEAT SA DE CV',
            'COMERWAVE SA DE CV',
            'INFINIA TECNOLOGIA Y SERVICIOS, S.A DE C.V.',
            'IDENTIDICACION ELECTRONICA Y AUTOMATIZACION S.A DE C.V.',
            'ABASTECEDOR TERAPEUTICO, S.A DE C.V.',
            'ELECTRONICA KETER MAZAL SA DE CV',
            'MUEBLEMUNDO',
            'HOSPITECNIA, S.A DE C.V.',
            'INOXIDABLE CEAL S DE R.L DE C.V',
            'ALEJANDRA BARRAZA HERNANDEZ',
            'FERBOLISA DE CV',
            'SOLUCIONES DIGITALES TECNOLOGICAS',
            'LUABFE DE MEXICO',
            'JUAN DIEGO SANCHEZ SANCHEZ',
            'JOSE FRANCISCO CASTILLO GUTIERREZ',
            'API GLOBAL',
            'CYBERPUERTA SA DE CV',
            'GRUPO DECME',
            'EQUIPO ELECTROMEDICO Y HOSPITALARIO DE MEXICO',
            'BAXTER SA DE CV',
            'TELECOMUNICACIONES INTERACTIVAS',
            'RIBONO',
            'COLCHONES VENTECK',
            'DISTRIBUIDORA BARMEX',
            'PISA EQUIPOS BIOMEDICOS',
            'COMERCIAL INDUSTRIAL ALVARADO',
            'EQUIPOS MEDICOS EL BISTURI',
            'HOSPITAL SAN SERAFIN',
            'HOSPITAL ANGELES',
            'ECODELI COMERCIAL',
            'SOLQUIMED',
            'OFFICE DEPOT DE MEXICO',
            'TINO',
            'GRUPO MORAVI',
            'RESPIRO2 SOLUCIONES EN OXIGENO',
            'PHILIPS MEXICO COMERCIAL SA DE CV',
            'CARAS PRODUCTOS CORPORACION',
            'GRUPO SIM',
            'INHALATEC',
            'MGC DIAGNOSTIC',
            'CEMER',
            'VAYVER',
            'ARMIN ALVARADO',
            'DR. VALLEJO HSS',
            'SERVICIOS DE INGENIERIA EN MEDICINA',
            'INTERCOMPRAS COMERCIO ELECTRONICO SA DE CV',
            'MI PC COM SA DE CV',
            'PROTECCE COMUNICACIONES SA DE CV',
            'KH SOLUCIONES EIT',
            'INFINIA TECNOLOGICA Y SERVICIOS SA DE CV',
            'AMBROSIA SOLUCIONES AMBIENTALES SA DE CV',
            'ENHU SUPPLIES S DE RL DE CV',
            'CRISTALERIA LA UNICA SA DE CV',
            'PROCOMSA',
            'COMERCIALIZADORA KELLY SA DE CV',
            'IMADINE equipos e insumos para imagenologia',
            'MERCADO LIBRE',
            'SKY WATER',
            'DONACION',
            'CARDIOPACE',
            'IKEA',
            'ARCOSHOP',
            'BIOMEDICA TINAJERO S DE RL DE CV',
            'AIRE Y EQUIPO PARA REFRIGERACION SA DE CV',
            'SGDJK ZGSUSI',
        ];

        $now = now();
        $data = [];

        foreach ($proveedores as $index => $proveedor) {
            $data[] = [
                'nombre_proveedor' => $proveedor,
                'razon_social' => $proveedor,
                'email_proveedor' => 'proveedor' . ($index + 1) . '@hss.local',
                'telefono_proveedor' => '3300000000',
                'sitioWeb' => null,
                'rfc' => 'RFC' . str_pad((string) ($index + 1), 9, '0', STR_PAD_LEFT),
                'estatus_activo' => true,
                'id_tipo_moneda' => 1,
                'id_tipo_proveedor' => 1,
                'id_forma_pago' => 1,
                'id_tipo_regimen' => 1,
                'id_tipo_descuento' => 1,
                'id_tipo_facturacion' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }

        DB::table('almacengeneral.tableAF_Proveedores')->insert($data);
    }
}
