<?php

namespace Database\Seeders\AlmacenGeneral;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class table_ProveedoresSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('almacengeneral.tableAF_Proveedores')->insert([
            [
                'nombre_proveedor' => 'Proveedor Uno',
                'razon_social' => 'Proveedor Uno S.A. de C.V.',
                'email_proveedor' => 'contacto1@proveedoruno.com',
                'telefono_proveedor' => '3312345678',
                'sitioWeb' => 'https://www.proveedoruno.com',
                'rfc' => 'PUO123456ABC',
                'id_tipo_moneda' => 1,
                'id_tipo_proveedor' => 1,
                'id_forma_pago' => 1,
                'id_tipo_regimen' => 1,
                'id_tipo_descuento' => 1,
                'id_tipo_facturacion' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_proveedor' => 'Proveedor Dos',
                'razon_social' => 'Proveedor Dos S.A. de C.V.',
                'email_proveedor' => 'contacto2@proveedordos.com',
                'telefono_proveedor' => '3323456789',
                'sitioWeb' => 'https://www.proveedordos.com',
                'rfc' => 'PDO234567DEF',
                'id_tipo_moneda' => 2,
                'id_tipo_proveedor' => 2,
                'id_forma_pago' => 2,
                'id_tipo_regimen' => 2,
                'id_tipo_descuento' => 2,
                'id_tipo_facturacion' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_proveedor' => 'Proveedor Tres',
                'razon_social' => 'Proveedor Tres S.A. de C.V.',
                'email_proveedor' => 'contacto3@proveedortres.com',
                'telefono_proveedor' => '3334567890',
                'sitioWeb' => 'https://www.proveedortres.com',
                'rfc' => 'PTR345678GHI',
                'id_tipo_moneda' => 1,
                'id_tipo_proveedor' => 1,
                'id_forma_pago' => 1,
                'id_tipo_regimen' => 1,
                'id_tipo_descuento' => 1,
                'id_tipo_facturacion' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_proveedor' => 'Proveedor Cuatro',
                'razon_social' => 'Proveedor Cuatro S.A. de C.V.',
                'email_proveedor' => 'contacto4@proveedorcuatro.com',
                'telefono_proveedor' => '3345678901',
                'sitioWeb' => 'https://www.proveedorcuatro.com',
                'rfc' => 'PCU456789JKL',
                'id_tipo_moneda' => 2,
                'id_tipo_proveedor' => 2,
                'id_forma_pago' => 2,
                'id_tipo_regimen' => 2,
                'id_tipo_descuento' => 2,
                'id_tipo_facturacion' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_proveedor' => 'Proveedor Cinco',
                'razon_social' => 'Proveedor Cinco S.A. de C.V.',
                'email_proveedor' => 'contacto5@proveedorcinco.com',
                'telefono_proveedor' => '3356789012',
                'sitioWeb' => 'https://www.proveedorcinco.com',
                'rfc' => 'PCI567890MNO',
                'id_tipo_moneda' => 1,
                'id_tipo_proveedor' => 1,
                'id_forma_pago' => 1,
                'id_tipo_regimen' => 1,
                'id_tipo_descuento' => 1,
                'id_tipo_facturacion' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_proveedor' => 'Proveedor Seis',
                'razon_social' => 'Proveedor Seis S.A. de C.V.',
                'email_proveedor' => 'contacto6@proveedorseis.com',
                'telefono_proveedor' => '3367890123',
                'sitioWeb' => 'https://www.proveedorseis.com',
                'rfc' => 'PSE678901PQR',
                'id_tipo_moneda' => 2,
                'id_tipo_proveedor' => 2,
                'id_forma_pago' => 2,
                'id_tipo_regimen' => 2,
                'id_tipo_descuento' => 2,
                'id_tipo_facturacion' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_proveedor' => 'Proveedor Siete',
                'razon_social' => 'Proveedor Siete S.A. de C.V.',
                'email_proveedor' => 'contacto7@proveedorsiete.com',
                'telefono_proveedor' => '3378901234',
                'sitioWeb' => 'https://www.proveedorsiete.com',
                'rfc' => 'PSI789012STU',
                'id_tipo_moneda' => 1,
                'id_tipo_proveedor' => 1,
                'id_forma_pago' => 1,
                'id_tipo_regimen' => 1,
                'id_tipo_descuento' => 1,
                'id_tipo_facturacion' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_proveedor' => 'Proveedor Ocho',
                'razon_social' => 'Proveedor Ocho S.A. de C.V.',
                'email_proveedor' => 'contacto8@proveedorocho.com',
                'telefono_proveedor' => '3389012345',
                'sitioWeb' => 'https://www.proveedorocho.com',
                'rfc' => 'POC890123VWX',
                'id_tipo_moneda' => 2,
                'id_tipo_proveedor' => 2,
                'id_forma_pago' => 2,
                'id_tipo_regimen' => 2,
                'id_tipo_descuento' => 2,
                'id_tipo_facturacion' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_proveedor' => 'Proveedor Nueve',
                'razon_social' => 'Proveedor Nueve S.A. de C.V.',
                'email_proveedor' => 'contacto9@proveedornueve.com',
                'telefono_proveedor' => '3390123456',
                'sitioWeb' => 'https://www.proveedornueve.com',
                'rfc' => 'PNU901234YZA',
                'id_tipo_moneda' => 1,
                'id_tipo_proveedor' => 1,
                'id_forma_pago' => 1,
                'id_tipo_regimen' => 1,
                'id_tipo_descuento' => 1,
                'id_tipo_facturacion' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre_proveedor' => 'Proveedor Diez',
                'razon_social' => 'Proveedor Diez S.A. de C.V.',
                'email_proveedor' => 'contacto10@proveedordiez.com',
                'telefono_proveedor' => '3312345670',
                'sitioWeb' => 'https://www.proveedordiez.com',
                'rfc' => 'PDI012345BCD',
                'id_tipo_moneda' => 2,
                'id_tipo_proveedor' => 2,
                'id_forma_pago' => 2,
                'id_tipo_regimen' => 2,
                'id_tipo_descuento' => 2,
                'id_tipo_facturacion' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
